getwd()
remove.packages("rstan")
if (file.exists(".RData")) file.remove(".RData")
install.packages("rstan", repos = "https://cloud.r-project.org/", dependencies = TRUE)
install.packages('ggplot2')
install.packages('xts')
pkgbuild::has_build_tools(debug = TRUE)
install.packages('quantmod')
install.packages('broom')
install.packages('rugarch')
install.packages('tibble')
install.packages("BatchGetSymbols")
install.packages("tidyverse")
install.packages("reshape")
install.packages("plotly")
install.packages("matrixStats")